/* 실전문제 3번 ~ 25번 */
/* 문제 3 */
ALTER TABLE SALGRADE ADD CONSTRAINTS pk_salgrade_grade PRIMARY KEY (GRADE);
--ALTER TABLE SALGRADE MODIFY GRADE NUMBER(9,2); ##정도 또는 자리수를 축소할 열은 비어 있어야 합니다##라고 뜸
DESC SALGRADE;
/* 문제 4 */
SELECT EMPNO, ENAME, JOB
FROM EMP;
/* 문제 6 */
SELECT DNAME, LOC
FROM DEPT;
/* 문제 8 */
SELECT DISTINCT HIREDATE
FROM EMP;
/* 문제 11 */
SELECT ENAME, SAL*6
FROM EMP;
/* 문제 12 */
SELECT ENAME, COMM*6
FROM EMP;
/* 문제 13 */
SELECT ENAME AS "NAME", SAL AS "SALARY"
FROM EMP;
/* 문제 14 */
SELECT EMPNO AS 사원번호, ENAME AS 사원이름, HIREDATE AS 입사일, DEPTNO AS 부서번호
FROM EMP;
/* 문제 17 */
SELECT HIREDATE ||'에 입사한 '||ENAME||'입니다.'
FROM EMP;
/* 문제 19 */
SELECT EMPNO, ENAME
FROM EMP
WHERE SAL >= 2000;
/* 문제 21 */
SELECT ENAME
FROM EMP
WHERE HIREDATE= '1980-12-17';
/* 문제 22 */
SELECT DNAME, LOC
FROM DEPT
WHERE DEPTNO <>30;
/* 문제 23 */
SELECT HISAL, LOSAL
FROM SALGRADE
WHERE GRADE = 5;
/* 문제 25 */
SELECT ENAME, JOB, DEPTNO
FROM EMP
WHERE DEPTNO=10 AND JOB = 'MANAGER';

/* 연습문제 짝수 공략 PP.112 ~ 119 */
/* 문제 2 */
DESC SUBJECT;
/* 문제 4 */
DESC ENROL;
/* 문제 6 */
SELECT SUB_NO, SUB_NAME
FROM SUBJECT;
/* 문제 8 */
SELECT *
FROM STUDENT;
/* 문제 10 */
SELECT SUB_NAME, SUB_PROF
FROM SUBJECT;
/* 문제 12 */
SELECT STU_NO, STU_NAME, STU_WEIGHT, STU_HEIGHT
FROM STUDENT;
/* 문제 14 */
SELECT DISTINCT STU_GENDER
FROM STUDENT;
/* 문제 16 */
SELECT DISTINCT STU_DEPT, STU_GRADE
FROM STUDENT;
/* 문제 18 */
SELECT STU_WEIGHT+5
FROM STUDENT;
/* 문제 20 */
SELECT STU_NO AS 학번, STU_NAME AS 이름
FROM STUDENT;
/* 문제 22 */
SELECT SUB_NAME AS 과목이름, SUB_PROF AS 교수명
FROM SUBJECT;
/* 문제 24 */
SELECT STU_DEPT||'과 '||STU_NAME||'입니다.'
FROM STUDENT;
/* 문제 26*/
SELECT *
FROM STUDENT
WHERE STU_DEPT = '기계';
/* 문제 28 */
SELECT *
FROM STUDENT
WHERE STU_HEIGHT >=170;
/* 문제 30 */
SELECT STU_NO, STU_NAME
FROM STUDENT
WHERE STU_DEPT='기계';
/* 문제 22 */
SELECT STU_NO, STU_NAME
FROM STUDENT
WHERE STU_DEPT = '전기전자';
/* 문제 34 */
SELECT *
FROM STUDENT
WHERE STU_GENDER = 'F';
/* 문제 36 */
SELECT *
FROM STUDENT
WHERE STU_DEPT <> '기계';
/* 문제 38 */
SELECT *
FROM STUDENT
WHERE STU_NAME='김인중';
/* 문제 40 */
SELECT *
FROM STUDENT
WHERE STU_DEPT='기계' AND STU_GRADE=2;
/* 문제 42 */
SELECT STU_NAME
FROM STUDENT
WHERE STU_DEPT <>'컴퓨터정보' AND STU_GRADE=1;
/* 문제 44 */
SELECT STU_NAME
FROM STUDENT
WHERE STU_DEPT = '컴퓨터정보' AND STU_GRADE=2 AND STU_CLASS= 'A';
/* 문제 46 */
SELECT STU_NO, STU_NAME, STU_DEPT
FROM STUDENT
WHERE STU_NO LIKE '2013%';
/* 문제 48 */
SELECT STU_NO, STU_NAME
FROM STUDENT
WHERE STU_NAME LIKE '김__';
/* 문제 50 */
SELECT *
FROM STUDENT;
WHERE STU_NO LIKE '2006%';
/* 문제 52 */
SELECT STU_NAME
FROM STUDENT
WHERE STU_HEIGHT IS NULL;
/* 문제 54 */
SELECT STU_NO, STU_NAME
FROM STUDENT
WHERE STU_DEPT = '컴퓨터정보' OR STU_DEPT= '기계';
/* 문제 56 */
SELECT STU_NO, STU_NAME
FROM STUDENT
ORDER BY STU_NO;
/* 문제 58 */
SELECT STU_NO, STU_NAME, STU_DEPT
FROM STUDENT
ORDER BY STU_DEPT, STU_NAME;
/* 문제 60 */
SELECT *
FROM STUDENT
ORDER BY STU_DEPT, STU_GENDER, STU_CLASS;
/* 문제 62 */
SELECT LOWER(STU_GENDER)
FROM STUDENT;
/* 문제 64 */
SELECT CONCAT(STU_DEPT, STU_NAME)
FROM STUDENT;
/* 문제 66 */
SELECT STU_NAME, SUBSTR(STU_NAME, 1,2)
FROM STUDENT;
/* 문제 68 */
SELECT STU_NAME,LENGTH(STU_NAME)
FROM STUDENT;
/* 문제 70 */
SELECT INSTR(STU_NAME,'김')
FROM STUDENT;
/* 문제 72 */
SELECT RPAD(STU_NAME, 15, '&')
FROM STUDENT;
/* 문제 74 */
SELECT STU_NO, STU_NAME, ROUND(STU_HEIGHT, 1)
FROM STUDENT;
/* 문제 76 */
SELECT MOD(STU_WEIGHT, 30)
FROM STUDENT;
/* 문제 78 */
SELECT STU_NO, STU_NAME, NVL(STU_HEIGHT, 0)+NVL(STU_WEIGHT, 0)
FROM STUDENT;
/* 문제 80 */
SELECT STU_NO, STU_NAME, NVL(TO_CHAR(STU_HEIGHT),'입력요망' )
FROM STUDENT;
/* 문제 82 */
SELECT STU_GENDER, NVL(NULLIF(STU_GENDER, 'M'), 'NULL')
FROM STUDENT
WHERE STU_GENDER = 'M';
/* 문제 84 */
SELECT STU_NO, STU_NAME, STU_GENDER, STU_WEIGHT,
    DECODE(STU_GENDER, 'F', STU_WEIGHT+5,
                        'M', STU_WEIGHT-5,
                        STU_WEIGHT) AS 변경된몸무게
FROM STUDENT;
/* 문제 86 */
SELECT MIN(STU_HEIGHT)
FROM STUDENT;
/* 문제 88 */
SELECT MAX(STU_NAME), MIN(STU_NAME)
FROM STUDENT;
/* 문제 90 */
SELECT MAX(STU_NO), MIN(STU_NO)
FROM STUDENT;
/* 문제 92 */
SELECT COUNT(DISTINCT SUBSTR(STU_NAME, 1,1))
FROM STUDENT;
/* 문제 94 */
SELECT COUNT(*)
FROM ENROL;
/* 문제 96 */
SELECT STU_DEPT, COUNT(STU_DEPT)
FROM STUDENT
GROUP BY STU_DEPT
ORDER BY COUNT(STU_DEPT) DESC;
/* 문제 98 */
SELECT STU_GRADE, COUNT(STU_GRADE)
FROM STUDENT
GROUP BY STU_GRADE
ORDER BY COUNT(STU_GRADE)  DESC;
/* 문제 100 */
SELECT STU_DEPT, ROUND(STDDEV(NVL(STU_WEIGHT,0)), 2)
FROM STUDENT
GROUP BY STU_DEPT;
/* 문제 102 */
SELECT STU_DEPT, STU_GRADE, AVG(STU_WEIGHT)
FROM STUDENT
GROUP BY STU_DEPT, STU_GRADE;
/* 문제 104 */
SELECT STU_DEPT, COUNT(*)
FROM STUDENT
GROUP BY STU_DEPT
ORDER BY COUNT(STU_DEPT) DESC;
/* 문제 106 */
SELECT STU_DEPT, STU_GRADE, AVG(STU_WEIGHT)
FROM STUDENT
GROUP BY STU_DEPT, STU_GRADE
ORDER BY AVG(STU_WEIGHT) DESC;
/* 문제 108 */
SELECT STU_DEPT, AVG(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_DEPT HAVING AVG(STU_HEIGHT)>=170;