/* 실전문제 PP.185-196 */
CREATE TABLE EMP1
AS SELECT * FROM EMP WHERE DEPTNO IN (20,30);

CREATE TABLE DEPT1
AS SELECT * FROM DEPT;

CREATE TABLE SALGRADE1
AS SELECT * FROM SALGRADE;

SELECT * FROM EMP1;

SELECT * FROM DEPT1;

SELECT * FROM SALGRADE1;

2.
INSERT INTO EMP1(EMPNO, ENAME, SAL, DEPTNO)
VALUES(7401, 'HOMER', 1300, 10);

SELECT * FROM EMP1;

4.
INSERT INTO EMP1
SELECT *
FROM EMP
WHERE DEPTNO = 10;

SELECT * FROM EMP1;

6.
UPDATE EMP1
SET SAL = SAL - SAL*0.1
WHERE DEPTNO = 20;

SELECT * FROM EMP1;

8. 
UPDATE EMP1
SET MGR = 7654, DEPTNO = 30
WHERE EMPNO = 7902;

SELECT * FROM EMP1;

10.
UPDATE EMP1
SET SAL = SAL-20
WHERE EMPNO IN (SELECT EMPNO 
                FROM EMP1, SALGRADE 
                WHERE SAL >= LOSAL AND SAL <= HISAL AND GRADE = 2);

SELECT * FROM EMP1;

12.
INSERT INTO DEPT1
VALUES ('50', 'PLANNING','MIAMI');

SELECT * FROM DEPT1;

14.
DELETE FROM DEPT1
WHERE DEPTNO = '30';

SELECT * FROM DEPT1;

16.
DELETE FROM EMP1
WHERE DEPTNO = '99';

SELECT * FROM EMP1;

18.
UPDATE EMP1
SET DEPTNO = '30'
WHERE ENAME IN ('JOSH','JONES','CLARK');

SELECT * FROM EMP1;

20.
DROP TABLE EMP1;
SELECT * FROM EMP1;

/* 연습문제 PP.197-199 */
CREATE TABLE STUDENT1
AS SELECT * FROM STUDENT WHERE STU_GRADE IN (1,2);

CREATE TABLE SUBJECT1
AS SELECT * FROM SUBJECT;

CREATE TABLE ENROL1
AS SELECT * FROM ENROL;

SELECT * FROM STUDENT1;
SELECT * FROM SUBJECT1;
SELECT * FROM ENROL1;

2.
INSERT INTO STUDENT1(STU_NO, STU_NAME, STU_DEPT, STU_GRADE, STU_CLASS, STU_GENDER)
VALUES('20102038', '남지선', '전기전자', 1, 'C', 'F');

SELECT * FROM STUDENT1;

4.
INSERT INTO STUDENT1
SELECT *
FROM STUDENT
WHERE STU_GRADE =3;

SELECT * FROM STUDENT1;

6.
UPDATE STUDENT1
SET STU_HEIGHT = STU_HEIGHT +2
WHERE STU_NO = '20131025';

SELECT * FROM STUDENT1;

10.
UPDATE ENROL1
SET ENR_GRADE = 0
WHERE STU_NO = '20151062';

SELECT * FROM ENROL1;

12.
INSERT INTO SUBJECT1(SUB_NO, SUB_NAME, SUB_PROF, SUB_GRADE, SUB_DEPT)
VALUES(112, '자동화시스템', '고종민', 3, '기계');

SELECT * FROM SUBJECT1;

14.
DELETE FROM SUBJECT1
WHERE SUB_NO = 101;

SELECT * FROM SUBJECT1;

16.
UPDATE ENROL1
SET STU_NO = '99999999'
WHERE ENROL1.STU_NO NOT IN (SELECT STU_NO FROM STUDENT1);

SELECT * FROM ENROL1;

18.
DELETE FROM ENROL1
WHERE STU_NO = '99999999';

SELECT * FROM ENROL1;

20.
DROP TABLE ENROL1;
SELECT * FROM ENROL1;